# age = int(input())   ITS RISKY CODE THAT IS GENERATED BY AI 

# CORRECT WAY IS :
# age = input('ENTER YOUR AGE : ')
# if age.isdigit():
#     if int(age) > 0:
#         print('YOUR AGE IS : ', age)    

# else:    print('PLEASE ENTER A VALID AGE')




# -----------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------


# SENITIZATION MEANS CLEANING THE CODE.
    # IF YOU OWN FACEBOOK AND PEOPLE COMMENT IN LIKE AFTER A HUGE SPACE LIKE 
    #         ABDUL QADEER       IT STORE DATABASE IN THE SPACE THAT LOOKS BAD SO FIRST WE CLEAN AND THEN STORE IT IN DATABASE.


# name = input('ENTER YOUR NAME : ')
# name = name.strip()                   # Remove leading and trailing whitespace
# print('YOUR NAME IS : ', name)
#THIS PROCESS IS CALLED SANITIZATION. IT IS USED TO CLEAN THE DATA BEFORE STORING IN DATABASE.
